baseurl = "https://nikolavp.github.io/"
languageCode = "en-us"
title = "Nikolavp's hacking"
pygmentsuseclasses = false


copyright = "Copyright (c) 2008 - 2016, Nikola Petrov; all rights reserved."
canonifyurls = true
paginate = 3
theme = "ananke"

[permalinks]
    post = "/blog/:year/:month/:day/:title/"

[author]
name = "Nikola Petrov"
email = "nikolavp@gmail.com"

[taxonomies]
category = "categories"

[indexes]
tag = "tags"
#topic = "topics"

[params]
# Properties for the lanyon theme
    Title = "Nikolavp's hacking"
    DateForm = "Jan 2 2006"
    Author = "Nikola Petrov"
    SyntaxHighlightTheme = "solarized_dark.min.css"
# site description, will show under navigation
    description = ""

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss = "/index.xml"
subscribe_email = ""

# social links
facebook_user = ""
googleplus_user = ""
twitter_user = ""
github_user = ""
coderwall_user = ""
stackoverflow_user = ""
stackoverflow_user_id = ""
linkedin_user = ""
pinterest_user = ""
delicious_user = ""
pinboard_user = ""
quora_user = ""
instagram_user = ""
behance_user = ""
douban_user = ""

# share links
facebook_like = true
twitter_tweet_button = true
google_plus_one = "true"
addthis_profile_id = ""

# Disqus Comments
disqus_short_name = ""
disqus_show_comment_count = false

# google analytics
google_analytics_tracking_id = ""
